import { assertSafeProbeUrl } from "../../../packages/monitor-core/src/url-safety";

interface Env { DB: D1Database; MONITOR_LIMIT?: string }
interface Endpoint { id:string; resource_id:string; url:string; method:string; timeout_ms:number }

function classifyError(error:unknown){const m=error instanceof Error?error.message.toLowerCase():"";if(m.includes("timeout"))return"timeout";if(m.includes("tls"))return"tls";if(m.includes("dns"))return"dns";return"connection"}
async function sha256(value:string){const bytes=new TextEncoder().encode(value);const hash=await crypto.subtle.digest("SHA-256",bytes);return[...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,"0")).join("")}
function structuralShape(value:unknown):unknown{if(Array.isArray(value))return value.length?[structuralShape(value[0])]:[];if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,structuralShape(v)]));return typeof value}

async function probe(endpoint:Endpoint){
  const url=assertSafeProbeUrl(endpoint.url);const started=performance.now();const controller=new AbortController();const timer=setTimeout(()=>controller.abort("timeout"),Math.min(endpoint.timeout_ms,15000));
  try{const response=await fetch(url,{method:endpoint.method==="HEAD"?"HEAD":"GET",redirect:"manual",signal:controller.signal,headers:{"User-Agent":"SA-Public-API-Observatory/1.0","Accept":"application/json, application/xml, text/csv;q=0.8, */*;q=0.2"}});if(response.status>=300&&response.status<400){const location=response.headers.get("location");if(location)assertSafeProbeUrl(new URL(location,url).toString())}
    const reader=response.body?.getReader();let size=0;const chunks:Uint8Array[]=[];while(reader){const{done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>1_000_000){await reader.cancel();break}chunks.push(value)}const body=new TextDecoder().decode(chunks.reduce((all,chunk)=>{const next=new Uint8Array(all.length+chunk.length);next.set(all);next.set(chunk,all.length);return next},new Uint8Array()));const contentType=response.headers.get("content-type")??"";let validPayload=size>20;let schemaHash:string|null=null;if(contentType.includes("json")){try{const parsed=JSON.parse(body);schemaHash=await sha256(JSON.stringify(structuralShape(parsed)))}catch{validPayload=false}}
    return{success:response.ok&&validPayload,httpStatus:response.status,latencyMs:Math.round((performance.now()-started)*10)/10,responseBytes:size,contentType,validationResult:validPayload?"valid":"invalid-payload",errorClass:response.ok?(validPayload?null:"invalid-payload"):`http-${Math.floor(response.status/100)}xx`,payloadHash:await sha256(body),schemaHash};
  }catch(error){return{success:false,httpStatus:null,latencyMs:Math.round((performance.now()-started)*10)/10,responseBytes:null,contentType:null,validationResult:"request-failed",errorClass:classifyError(error),payloadHash:null,schemaHash:null}}finally{clearTimeout(timer)}
}

async function run(env:Env){const limit=Math.min(25,Math.max(1,Number(env.MONITOR_LIMIT??10)));const{results=[]}=await env.DB.prepare("SELECT id, resource_id, url, method, timeout_ms FROM endpoints WHERE enabled = 1 ORDER BY id LIMIT ?").bind(limit).all<Endpoint>();let completed=0;for(const endpoint of results){const result=await probe(endpoint);const id=crypto.randomUUID(),observedAt=new Date().toISOString();await env.DB.prepare("INSERT INTO measurements (id, endpoint_id, observed_at, success, http_status, latency_ms, response_bytes, content_type, validation_result, error_class, payload_hash, schema_hash, freshness_timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NULL)").bind(id,endpoint.id,observedAt,result.success?1:0,result.httpStatus,result.latencyMs,result.responseBytes,result.contentType,result.validationResult,result.errorClass,result.payloadHash,result.schemaHash).run();completed++}await env.DB.prepare("INSERT INTO system_state (key,value,updated_at) VALUES ('last_monitor_cycle',?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at").bind(JSON.stringify({completed}),new Date().toISOString()).run();return{completed}}

const monitorWorker={async scheduled(_controller:ScheduledController,env:Env,ctx:ExecutionContext){ctx.waitUntil(run(env))},async fetch(request:Request,env:Env){if(new URL(request.url).pathname!=="/health")return new Response("Not found",{status:404});const row=await env.DB.prepare("SELECT value,updated_at FROM system_state WHERE key='last_monitor_cycle'").first();return Response.json({service:"monitor",last_cycle:row??null})}};
export default monitorWorker;
